<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>Empty</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="dotenv.net" Version="4.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Supabase" Version="8.1.1" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="scripts\database\" />
  </ItemGroup>
  <ItemGroup>
    <Content Include=".env" />
  </ItemGroup>
</Project>